services:
  app:
    image: mcr.microsoft.com/devcontainers/go:1-1.24-bookworm
    container_name: devcontainer_karakeepbot
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  karakeep:
    image: ghcr.io/karakeep-app/karakeep:0.26.0
    container_name: devcontainer_karakeep
    volumes:
      - karakeep_data:/data
    env_file:
      - .env
    environment:
      DATA_DIR: /data
      NEXTAUTH_SECRET: super_random_string
    ports:
      - 3000:3000

volumes:
  karakeep_data:
